### PR TITLE
Add an interesting new service for datacentre energy management

### PR DESCRIPTION
**Pull request by mrchrisadams**
I came across this tool this week - a specific service for managing compute energy consumption at the datacentre level for on-prem folks.

### CODE REVIEW

**Comment by mrchrisadams** [comment]
I couldn't tell from the contribution guidelines which branch I ought to make the PR for - if I need to to a PR against a different branch, would you let me know?

https://github.com/Green-Software-Foundation/awesome-green-software/blob/main/contributing.md

**Comment by dtoakley-tw** [comment]
Thanks @mrchrisadams -- this is great! Could you update your PR in two ways for me:

1. Point it to the `dev` branch. I'll get the contributing updated with this info. 
2. Move the entry to be alphabetically in order within the same section. I believe this is after the `carbontracker` entry. 

Thanks again!

**Comment by mrchrisadams** [comment]
Sup @dtoakley I've made these changes. Ta!

**Comment by dtoakley-tw** [comment]
LGTM -- Merging!

**Pull request merged**
