### PR TITLE
Hardware Sentry, ecoIndex and ToC update

### PR DESCRIPTION
**Pull request by bertysentry**
* Added Hardware Sentry in General/Energy
* Moved CO2Scope from AI/Energy to General/Energy
* Added ecoIndex.fr to OS based/Web
* Updated ToC

### CODE REVIEW

**Comment by bertysentry** [comment]
Disclosure: I work with Sentry Software, the company that develops Hardware Sentry. The product is free to use, but not open sourced yet (it's quite a complicated matter, but it's coming!)

**Comment by dtoakley-tw** [comment]
Hey @bertysentry -- thanks so much for this PR, and apologies for the delay. Overall this looks good -- but there some merge conflicts -- sorry, that was probably due to a recent change by me. Could you resolve that before I merge to the `dev` branch? 

Thanks for noticing the TOC changes, and it looks like some section are out of alphabetical order. I'll fix that after this is merged, so no need for you to worry about it. 

And thanks for the disclosure. It looks like the Hardware Sentry documentation sufficiently references the sustainability features as being fairly core to the product, so I think it's okay for the list. A non-blocking question though -- do you have a timeline for when it might be open sourced? When that does happen, I think we'll want to update the entry to point to the open source code/documentation.

**Comment by bertysentry** [comment]
Hi @dtoakley-tw, I'll look into the conflict.

WRT Hardware Sentry open source, it takes some time because we first have to open-source its dependencies, fix the build pipeline for these, publish the artifacts. So it's an iterative process. Most probable scenario is that we're going to open-source its next major version (very exciting!) that we already started working on. All in all, our goal is to have that open-source by the end of the year!

**Comment by dtoakley-tw** [comment]
LGTM -- thanks again @bertysentry

**Pull request merged**
