### PR TITLE
Latest release from dev branch 

### PR DESCRIPTION
**Pull request by dtoakley-tw**

### CODE REVIEW

**Comment by dtoakley-tw** [comment]
Hey @atg-abhishek, @ahkok, @martatorredev and @twobiers -- In order to merge this dev branch to main, y'all need to add a DCO remediation commit. You can find details and example commits here: https://github.com/Green-Software-Foundation/awesome-green-software/pull/108/checks?check_run_id=13100599987 --  would you be able to action this, and confirm  with a comment on the PR? 

@bertysentry -- I know you had trouble doing this, so I'm going to reach out via email and organize a time for use to pair on it together, if that is okay?

**Comment by bertysentry** [comment]
@dtoakley-tw I'm surprised by the error message:

> Commit sha: [12bd41c](https://github.com/Green-Software-Foundation/awesome-green-software/pull/108/commits/12bd41c2980b3ff303a5b40f34f9404681a32673), Author: Bertrand Martin, Committer: GitHub; Expected "Bertrand Martin [32521698+bertysentry@users.noreply.github.com](mailto:32521698+bertysentry@users.noreply.github.com)", but got "Bertrand Martin [bertrand@sentrysoftware.com](mailto:bertrand@sentrysoftware.com)"

I signed off with my real email address, is that a problem? If someone needs to contact me about the changes I committed to this repo, they'd better use the email I indicated, instead of ~~32521698+bertysentry@users.noreply.github.com~~.

**Comment by twobiers** [comment]
@dtoakley-tw done in 35bcde7afbb75fdcdbb8bb4dbf013bf3e6f236c8. Would you mind clarifying the requirements in the Contribution Guidelines?

**Comment by dtoakley-tw** [comment]
So sorry for the delay in getting back to this. 

@atg-abhishek, @ahkok  and @martatorredev -- would you be able to create PRs pointing the dev branch with the remediation commits? Details here on how to do this are here: https://github.com/Green-Software-Foundation/awesome-green-software/pull/108/checks?check_run_id=15273094758

@twobiers -- thank you! Could you create a PR with that remediation commit pointed to the dev branch? I'ver also updated the contributing.md file with note about this.

**Comment by prof-antar** [comment]
reconciled as part of the backlog clearing

**Pull request closed without merging**
