### PR TITLE
Added Auto Scaling section with KEDA

### PR DESCRIPTION
**Pull request by rossf7**
Hi,
first of all thanks for creating this list! I love it. 

I have a question. Are auto scaling tools within scope?

If so then I think [KEDA](https://keda.sh/) is a good candidate. It supports scaling based on a [wide range](https://keda.sh/docs/2.5/concepts/#event-sources-and-scalers) of events. As well as scaling to zero which is hard to do with the standard Kubernetes [HPA](https://github.com/kubernetes/kubernetes/issues/69687) (horizontal pod autoscaler).

### CODE REVIEW

**Comment by rossf7** [comment]
Hi @dtoakley, could you take a look?

Do you think an autoscaling section and KEDA makes sense for the list?

**Comment by dtoakley** [comment]
Hey @rossf7 -- deepest apologies for the delayed response. So I'm not sure autoscaling tools should be on the list. While autoscaling is definitely a possible tactic to reduce the energy consumption and carbon emissions related to software, I would say there are also other categories of tactics that are similarly related, and I'm weary of the list drifting too far from being specifically about green software research, tools, libraries and trainings. For example serverless tools or cost optimization tools could be similar categories of tactics, and I think the categories would start to get a bit too broad if we include the tooling around them.  

That said, if there is a specific library or feature of KEDA that is focused on measuring or reducing energy and/or carbon emissions from Kubernetes, I think that could be a good candidate. I hope that makes sense -- let me know what you think!

**Comment by rossf7** [comment]
Hi @dtoakley, no worries and thanks for the response.

> I'm weary of the list drifting too far from being specifically about green software research, tools, libraries and trainings. 

Yes, this makes total sense to me. Autoscaling might be being used for cost reduction or handling load spikes instead of reducing energy usage.

> That said, if there is a specific library or feature of KEDA that is focused on measuring or reducing energy and/or carbon emissions from Kubernetes

The scale to zero support is the closest feature I can think of but it might also be used for cost reduction.

I'm going to close but I love the list and if I find a more suitable link I'll be back.

**Comment by tomkerkhove** [comment]
We try to help reduce compute waste through scale-to-zero in KEDA indeed

**Pull request closed without merging**
